/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./db-schemas";
export type Public_TitleStatus_Enum = z.infer<
  typeof generated.publicTitleStatusSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type Public_EmployeeTitles_Row = z.infer<
  typeof generated.publicEmployeeTitlesRowSchema
>;
export type Public_EmployeeTitles_Insert = z.infer<
  typeof generated.publicEmployeeTitlesInsertSchema
>;
export type Public_EmployeeTitles_Update = z.infer<
  typeof generated.publicEmployeeTitlesUpdateSchema
>;
export type Public_EmployeeTitles_Relationships = z.infer<
  typeof generated.publicEmployeeTitlesRelationshipsSchema
>;
export type Public_Employees_Row = z.infer<
  typeof generated.publicEmployeesRowSchema
>;
export type Public_Employees_Insert = z.infer<
  typeof generated.publicEmployeesInsertSchema
>;
export type Public_Employees_Update = z.infer<
  typeof generated.publicEmployeesUpdateSchema
>;
export type Public_PayPeriods_Row = z.infer<
  typeof generated.publicPayPeriodsRowSchema
>;
export type Public_PayPeriods_Insert = z.infer<
  typeof generated.publicPayPeriodsInsertSchema
>;
export type Public_PayPeriods_Update = z.infer<
  typeof generated.publicPayPeriodsUpdateSchema
>;
export type Public_Permissions_Row = z.infer<
  typeof generated.publicPermissionsRowSchema
>;
export type Public_Permissions_Insert = z.infer<
  typeof generated.publicPermissionsInsertSchema
>;
export type Public_Permissions_Update = z.infer<
  typeof generated.publicPermissionsUpdateSchema
>;
export type Public_StartingBalances_Row = z.infer<
  typeof generated.publicStartingBalancesRowSchema
>;
export type Public_StartingBalances_Insert = z.infer<
  typeof generated.publicStartingBalancesInsertSchema
>;
export type Public_StartingBalances_Update = z.infer<
  typeof generated.publicStartingBalancesUpdateSchema
>;
export type Public_StartingBalances_Relationships = z.infer<
  typeof generated.publicStartingBalancesRelationshipsSchema
>;
export type Public_TimeTypes_Row = z.infer<
  typeof generated.publicTimeTypesRowSchema
>;
export type Public_TimeTypes_Insert = z.infer<
  typeof generated.publicTimeTypesInsertSchema
>;
export type Public_TimeTypes_Update = z.infer<
  typeof generated.publicTimeTypesUpdateSchema
>;
export type Public_TimesheetEmployeeTimes_Row = z.infer<
  typeof generated.publicTimesheetEmployeeTimesRowSchema
>;
export type Public_TimesheetEmployeeTimes_Insert = z.infer<
  typeof generated.publicTimesheetEmployeeTimesInsertSchema
>;
export type Public_TimesheetEmployeeTimes_Update = z.infer<
  typeof generated.publicTimesheetEmployeeTimesUpdateSchema
>;
export type Public_TimesheetEmployeeTimes_Relationships = z.infer<
  typeof generated.publicTimesheetEmployeeTimesRelationshipsSchema
>;
export type Public_TimesheetEmployees_Row = z.infer<
  typeof generated.publicTimesheetEmployeesRowSchema
>;
export type Public_TimesheetEmployees_Insert = z.infer<
  typeof generated.publicTimesheetEmployeesInsertSchema
>;
export type Public_TimesheetEmployees_Update = z.infer<
  typeof generated.publicTimesheetEmployeesUpdateSchema
>;
export type Public_TimesheetEmployees_Relationships = z.infer<
  typeof generated.publicTimesheetEmployeesRelationshipsSchema
>;
export type Public_Timesheets_Row = z.infer<
  typeof generated.publicTimesheetsRowSchema
>;
export type Public_Timesheets_Insert = z.infer<
  typeof generated.publicTimesheetsInsertSchema
>;
export type Public_Timesheets_Update = z.infer<
  typeof generated.publicTimesheetsUpdateSchema
>;
export type Public_Timesheets_Relationships = z.infer<
  typeof generated.publicTimesheetsRelationshipsSchema
>;
export type Public_Titles_Row = z.infer<typeof generated.publicTitlesRowSchema>;
export type Public_Titles_Insert = z.infer<
  typeof generated.publicTitlesInsertSchema
>;
export type Public_Titles_Update = z.infer<
  typeof generated.publicTitlesUpdateSchema
>;
export type Public_UserPermissions_Row = z.infer<
  typeof generated.publicUserPermissionsRowSchema
>;
export type Public_UserPermissions_Insert = z.infer<
  typeof generated.publicUserPermissionsInsertSchema
>;
export type Public_UserPermissions_Update = z.infer<
  typeof generated.publicUserPermissionsUpdateSchema
>;
export type Public_UserPermissions_Relationships = z.infer<
  typeof generated.publicUserPermissionsRelationshipsSchema
>;
export type PublicDecryptSsnArgs = z.infer<
  typeof generated.publicDecryptSsnArgsSchema
>;
export type PublicDecryptSsnReturns = z.infer<
  typeof generated.publicDecryptSsnReturnsSchema
>;
export type PublicEmployeeUserIdArgs = z.infer<
  typeof generated.publicEmployeeUserIdArgsSchema
>;
export type PublicEmployeeUserIdReturns = z.infer<
  typeof generated.publicEmployeeUserIdReturnsSchema
>;
export type PublicGetEmployeeIdArgs = z.infer<
  typeof generated.publicGetEmployeeIdArgsSchema
>;
export type PublicGetEmployeeIdReturns = z.infer<
  typeof generated.publicGetEmployeeIdReturnsSchema
>;
export type PublicHasPermissionArgs = z.infer<
  typeof generated.publicHasPermissionArgsSchema
>;
export type PublicHasPermissionReturns = z.infer<
  typeof generated.publicHasPermissionReturnsSchema
>;
export type PublicVerifyTimesheetDateArgs = z.infer<
  typeof generated.publicVerifyTimesheetDateArgsSchema
>;
export type PublicVerifyTimesheetDateReturns = z.infer<
  typeof generated.publicVerifyTimesheetDateReturnsSchema
>;
