/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimesheetsRouteRouteImport } from './routes/timesheets/route'
import { Route as EmployeePortalRouteRouteImport } from './routes/employee-portal/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as TimesheetsIndexRouteImport } from './routes/timesheets/index'
import { Route as EmployeePortalIndexRouteImport } from './routes/employee-portal/index'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as TimesheetsHolidaysRouteImport } from './routes/timesheets/holidays'
import { Route as TimesheetsChangelogRouteImport } from './routes/timesheets/changelog'
import { Route as EmployeePortalProfileRouteImport } from './routes/employee-portal/profile'
import { Route as EmployeePortalChangelogRouteImport } from './routes/employee-portal/changelog'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as TimesheetsPayPeriodsRouteRouteImport } from './routes/timesheets/pay-periods/route'
import { Route as TimesheetsPayPeriodsIndexRouteImport } from './routes/timesheets/pay-periods/index'
import { Route as TimesheetsPayPeriodsYearIndexRouteImport } from './routes/timesheets/pay-periods/$year/index'
import { Route as TimesheetsPayPeriodsYearPpRouteImport } from './routes/timesheets/pay-periods/$year/$pp'
import { Route as TimesheetsPayPeriodsYearPpDateRouteImport } from './routes/timesheets/pay-periods/$year.$pp.$date'

const TimesheetsRouteRoute = TimesheetsRouteRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeePortalRouteRoute = EmployeePortalRouteRouteImport.update({
  id: '/employee-portal',
  path: '/employee-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetsIndexRoute = TimesheetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimesheetsRouteRoute,
} as any)
const EmployeePortalIndexRoute = EmployeePortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeePortalRouteRoute,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const TimesheetsHolidaysRoute = TimesheetsHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => TimesheetsRouteRoute,
} as any)
const TimesheetsChangelogRoute = TimesheetsChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => TimesheetsRouteRoute,
} as any)
const EmployeePortalProfileRoute = EmployeePortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeePortalRouteRoute,
} as any)
const EmployeePortalChangelogRoute = EmployeePortalChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => EmployeePortalRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const TimesheetsPayPeriodsRouteRoute =
  TimesheetsPayPeriodsRouteRouteImport.update({
    id: '/pay-periods',
    path: '/pay-periods',
    getParentRoute: () => TimesheetsRouteRoute,
  } as any)
const TimesheetsPayPeriodsIndexRoute =
  TimesheetsPayPeriodsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TimesheetsPayPeriodsRouteRoute,
  } as any)
const TimesheetsPayPeriodsYearIndexRoute =
  TimesheetsPayPeriodsYearIndexRouteImport.update({
    id: '/$year/',
    path: '/$year/',
    getParentRoute: () => TimesheetsPayPeriodsRouteRoute,
  } as any)
const TimesheetsPayPeriodsYearPpRoute =
  TimesheetsPayPeriodsYearPpRouteImport.update({
    id: '/$year/$pp',
    path: '/$year/$pp',
    getParentRoute: () => TimesheetsPayPeriodsRouteRoute,
  } as any)
const TimesheetsPayPeriodsYearPpDateRoute =
  TimesheetsPayPeriodsYearPpDateRouteImport.update({
    id: '/$date',
    path: '/$date',
    getParentRoute: () => TimesheetsPayPeriodsYearPpRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/employee-portal': typeof EmployeePortalRouteRouteWithChildren
  '/timesheets': typeof TimesheetsRouteRouteWithChildren
  '/timesheets/pay-periods': typeof TimesheetsPayPeriodsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/employee-portal/changelog': typeof EmployeePortalChangelogRoute
  '/employee-portal/profile': typeof EmployeePortalProfileRoute
  '/timesheets/changelog': typeof TimesheetsChangelogRoute
  '/timesheets/holidays': typeof TimesheetsHolidaysRoute
  '/': typeof appIndexRoute
  '/employee-portal/': typeof EmployeePortalIndexRoute
  '/timesheets/': typeof TimesheetsIndexRoute
  '/timesheets/pay-periods/': typeof TimesheetsPayPeriodsIndexRoute
  '/timesheets/pay-periods/$year/$pp': typeof TimesheetsPayPeriodsYearPpRouteWithChildren
  '/timesheets/pay-periods/$year': typeof TimesheetsPayPeriodsYearIndexRoute
  '/timesheets/pay-periods/$year/$pp/$date': typeof TimesheetsPayPeriodsYearPpDateRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/employee-portal/changelog': typeof EmployeePortalChangelogRoute
  '/employee-portal/profile': typeof EmployeePortalProfileRoute
  '/timesheets/changelog': typeof TimesheetsChangelogRoute
  '/timesheets/holidays': typeof TimesheetsHolidaysRoute
  '/': typeof appIndexRoute
  '/employee-portal': typeof EmployeePortalIndexRoute
  '/timesheets': typeof TimesheetsIndexRoute
  '/timesheets/pay-periods': typeof TimesheetsPayPeriodsIndexRoute
  '/timesheets/pay-periods/$year/$pp': typeof TimesheetsPayPeriodsYearPpRouteWithChildren
  '/timesheets/pay-periods/$year': typeof TimesheetsPayPeriodsYearIndexRoute
  '/timesheets/pay-periods/$year/$pp/$date': typeof TimesheetsPayPeriodsYearPpDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/employee-portal': typeof EmployeePortalRouteRouteWithChildren
  '/timesheets': typeof TimesheetsRouteRouteWithChildren
  '/timesheets/pay-periods': typeof TimesheetsPayPeriodsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/employee-portal/changelog': typeof EmployeePortalChangelogRoute
  '/employee-portal/profile': typeof EmployeePortalProfileRoute
  '/timesheets/changelog': typeof TimesheetsChangelogRoute
  '/timesheets/holidays': typeof TimesheetsHolidaysRoute
  '/(app)/': typeof appIndexRoute
  '/employee-portal/': typeof EmployeePortalIndexRoute
  '/timesheets/': typeof TimesheetsIndexRoute
  '/timesheets/pay-periods/': typeof TimesheetsPayPeriodsIndexRoute
  '/timesheets/pay-periods/$year/$pp': typeof TimesheetsPayPeriodsYearPpRouteWithChildren
  '/timesheets/pay-periods/$year/': typeof TimesheetsPayPeriodsYearIndexRoute
  '/timesheets/pay-periods/$year/$pp/$date': typeof TimesheetsPayPeriodsYearPpDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/employee-portal'
    | '/timesheets'
    | '/timesheets/pay-periods'
    | '/login'
    | '/employee-portal/changelog'
    | '/employee-portal/profile'
    | '/timesheets/changelog'
    | '/timesheets/holidays'
    | '/'
    | '/employee-portal/'
    | '/timesheets/'
    | '/timesheets/pay-periods/'
    | '/timesheets/pay-periods/$year/$pp'
    | '/timesheets/pay-periods/$year'
    | '/timesheets/pay-periods/$year/$pp/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/employee-portal/changelog'
    | '/employee-portal/profile'
    | '/timesheets/changelog'
    | '/timesheets/holidays'
    | '/'
    | '/employee-portal'
    | '/timesheets'
    | '/timesheets/pay-periods'
    | '/timesheets/pay-periods/$year/$pp'
    | '/timesheets/pay-periods/$year'
    | '/timesheets/pay-periods/$year/$pp/$date'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/employee-portal'
    | '/timesheets'
    | '/timesheets/pay-periods'
    | '/(auth)/login'
    | '/employee-portal/changelog'
    | '/employee-portal/profile'
    | '/timesheets/changelog'
    | '/timesheets/holidays'
    | '/(app)/'
    | '/employee-portal/'
    | '/timesheets/'
    | '/timesheets/pay-periods/'
    | '/timesheets/pay-periods/$year/$pp'
    | '/timesheets/pay-periods/$year/'
    | '/timesheets/pay-periods/$year/$pp/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  EmployeePortalRouteRoute: typeof EmployeePortalRouteRouteWithChildren
  TimesheetsRouteRoute: typeof TimesheetsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timesheets': {
      id: '/timesheets'
      path: '/timesheets'
      fullPath: '/timesheets'
      preLoaderRoute: typeof TimesheetsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-portal': {
      id: '/employee-portal'
      path: '/employee-portal'
      fullPath: '/employee-portal'
      preLoaderRoute: typeof EmployeePortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheets/': {
      id: '/timesheets/'
      path: '/'
      fullPath: '/timesheets/'
      preLoaderRoute: typeof TimesheetsIndexRouteImport
      parentRoute: typeof TimesheetsRouteRoute
    }
    '/employee-portal/': {
      id: '/employee-portal/'
      path: '/'
      fullPath: '/employee-portal/'
      preLoaderRoute: typeof EmployeePortalIndexRouteImport
      parentRoute: typeof EmployeePortalRouteRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/timesheets/holidays': {
      id: '/timesheets/holidays'
      path: '/holidays'
      fullPath: '/timesheets/holidays'
      preLoaderRoute: typeof TimesheetsHolidaysRouteImport
      parentRoute: typeof TimesheetsRouteRoute
    }
    '/timesheets/changelog': {
      id: '/timesheets/changelog'
      path: '/changelog'
      fullPath: '/timesheets/changelog'
      preLoaderRoute: typeof TimesheetsChangelogRouteImport
      parentRoute: typeof TimesheetsRouteRoute
    }
    '/employee-portal/profile': {
      id: '/employee-portal/profile'
      path: '/profile'
      fullPath: '/employee-portal/profile'
      preLoaderRoute: typeof EmployeePortalProfileRouteImport
      parentRoute: typeof EmployeePortalRouteRoute
    }
    '/employee-portal/changelog': {
      id: '/employee-portal/changelog'
      path: '/changelog'
      fullPath: '/employee-portal/changelog'
      preLoaderRoute: typeof EmployeePortalChangelogRouteImport
      parentRoute: typeof EmployeePortalRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/timesheets/pay-periods': {
      id: '/timesheets/pay-periods'
      path: '/pay-periods'
      fullPath: '/timesheets/pay-periods'
      preLoaderRoute: typeof TimesheetsPayPeriodsRouteRouteImport
      parentRoute: typeof TimesheetsRouteRoute
    }
    '/timesheets/pay-periods/': {
      id: '/timesheets/pay-periods/'
      path: '/'
      fullPath: '/timesheets/pay-periods/'
      preLoaderRoute: typeof TimesheetsPayPeriodsIndexRouteImport
      parentRoute: typeof TimesheetsPayPeriodsRouteRoute
    }
    '/timesheets/pay-periods/$year/': {
      id: '/timesheets/pay-periods/$year/'
      path: '/$year'
      fullPath: '/timesheets/pay-periods/$year'
      preLoaderRoute: typeof TimesheetsPayPeriodsYearIndexRouteImport
      parentRoute: typeof TimesheetsPayPeriodsRouteRoute
    }
    '/timesheets/pay-periods/$year/$pp': {
      id: '/timesheets/pay-periods/$year/$pp'
      path: '/$year/$pp'
      fullPath: '/timesheets/pay-periods/$year/$pp'
      preLoaderRoute: typeof TimesheetsPayPeriodsYearPpRouteImport
      parentRoute: typeof TimesheetsPayPeriodsRouteRoute
    }
    '/timesheets/pay-periods/$year/$pp/$date': {
      id: '/timesheets/pay-periods/$year/$pp/$date'
      path: '/$date'
      fullPath: '/timesheets/pay-periods/$year/$pp/$date'
      preLoaderRoute: typeof TimesheetsPayPeriodsYearPpDateRouteImport
      parentRoute: typeof TimesheetsPayPeriodsYearPpRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface EmployeePortalRouteRouteChildren {
  EmployeePortalChangelogRoute: typeof EmployeePortalChangelogRoute
  EmployeePortalProfileRoute: typeof EmployeePortalProfileRoute
  EmployeePortalIndexRoute: typeof EmployeePortalIndexRoute
}

const EmployeePortalRouteRouteChildren: EmployeePortalRouteRouteChildren = {
  EmployeePortalChangelogRoute: EmployeePortalChangelogRoute,
  EmployeePortalProfileRoute: EmployeePortalProfileRoute,
  EmployeePortalIndexRoute: EmployeePortalIndexRoute,
}

const EmployeePortalRouteRouteWithChildren =
  EmployeePortalRouteRoute._addFileChildren(EmployeePortalRouteRouteChildren)

interface TimesheetsPayPeriodsYearPpRouteChildren {
  TimesheetsPayPeriodsYearPpDateRoute: typeof TimesheetsPayPeriodsYearPpDateRoute
}

const TimesheetsPayPeriodsYearPpRouteChildren: TimesheetsPayPeriodsYearPpRouteChildren =
  {
    TimesheetsPayPeriodsYearPpDateRoute: TimesheetsPayPeriodsYearPpDateRoute,
  }

const TimesheetsPayPeriodsYearPpRouteWithChildren =
  TimesheetsPayPeriodsYearPpRoute._addFileChildren(
    TimesheetsPayPeriodsYearPpRouteChildren,
  )

interface TimesheetsPayPeriodsRouteRouteChildren {
  TimesheetsPayPeriodsIndexRoute: typeof TimesheetsPayPeriodsIndexRoute
  TimesheetsPayPeriodsYearPpRoute: typeof TimesheetsPayPeriodsYearPpRouteWithChildren
  TimesheetsPayPeriodsYearIndexRoute: typeof TimesheetsPayPeriodsYearIndexRoute
}

const TimesheetsPayPeriodsRouteRouteChildren: TimesheetsPayPeriodsRouteRouteChildren =
  {
    TimesheetsPayPeriodsIndexRoute: TimesheetsPayPeriodsIndexRoute,
    TimesheetsPayPeriodsYearPpRoute:
      TimesheetsPayPeriodsYearPpRouteWithChildren,
    TimesheetsPayPeriodsYearIndexRoute: TimesheetsPayPeriodsYearIndexRoute,
  }

const TimesheetsPayPeriodsRouteRouteWithChildren =
  TimesheetsPayPeriodsRouteRoute._addFileChildren(
    TimesheetsPayPeriodsRouteRouteChildren,
  )

interface TimesheetsRouteRouteChildren {
  TimesheetsPayPeriodsRouteRoute: typeof TimesheetsPayPeriodsRouteRouteWithChildren
  TimesheetsChangelogRoute: typeof TimesheetsChangelogRoute
  TimesheetsHolidaysRoute: typeof TimesheetsHolidaysRoute
  TimesheetsIndexRoute: typeof TimesheetsIndexRoute
}

const TimesheetsRouteRouteChildren: TimesheetsRouteRouteChildren = {
  TimesheetsPayPeriodsRouteRoute: TimesheetsPayPeriodsRouteRouteWithChildren,
  TimesheetsChangelogRoute: TimesheetsChangelogRoute,
  TimesheetsHolidaysRoute: TimesheetsHolidaysRoute,
  TimesheetsIndexRoute: TimesheetsIndexRoute,
}

const TimesheetsRouteRouteWithChildren = TimesheetsRouteRoute._addFileChildren(
  TimesheetsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  EmployeePortalRouteRoute: EmployeePortalRouteRouteWithChildren,
  TimesheetsRouteRoute: TimesheetsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
